# --- build Angular ---
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# --- serve with nginx ---
FROM nginx:1.25-alpine
# arquivos estáticos da SPA
COPY --from=build /app/dist/front-end /usr/share/nginx/html
EXPOSE 80
