services:
  db:
    image: postgres:16
    container_name: postgres-tinnova
    environment:
      POSTGRES_USER: tinnova
      POSTGRES_PASSWORD: tinnova
      POSTGRES_DB: tinnova
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d